name = "swiftpay-backend"
main = "src/index.ts"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# JWT_SECRET should be set via GitHub Secrets or Wrangler Secret

[[kv_namespaces]]
binding = "KV"
id = "5242d93100864c21840fbdf0a32a172b"

[[d1_databases]]
binding = "DB"
database_name = "swiftpay-db"
database_id = "f4238060-8914-41ab-a1a6-57195841aa00"
migrations_dir = "migrations"

[observability]
enabled = true
head_sampling_rate = 1
